spring.config.import=optional:application-local.properties

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App configs
app.otp.expire-minutes=${OTP_EXPIRE:5}
app.otp.length=${OTP_LENGTH:6}

# Static files
#spring.web.resources.static-locations=${STATIC_PATH}

# Server
server.address=0.0.0.0
server.port=${PORT:10000}

### Supabase config
supabase.url=${SUPABASE_URL}
supabase.service_role_key=${SUPABASE_SERVICE_ROLE_KEY}
supabase.bucket=${SUPABASE_BUCKET}

### VNPAY config
vnp.payUrl=${VNPAY_PAY_URL}
vnp.queryUrl=${VNPAY_QUERY_URL}
vnp.tmnCode=${VNPAY_TMN_CODE}
vnp.hashSecret=${VNPAY_HASH_SECRET}
vnp.returnUrl=${VNPAY_RETURN_URL}
vnp.ipnUrl=${VNPAY_IPN_URL}

